### ISSUE TITLE
Get the variable car['car_image'] to work in the garage_new

### ISSUE THREAD

**Issue by williambsm** [redman-racer/street_car_life#4]
Here is a step by step of how you should do it:

1. Create the function carThumbnail in the Car Manager like the other issue specifies.
2. In garageAjax.php, you will need to loop through every car in $user_cars.
3. In the loop, manually add $car['car_image'] = $car->carThumbnail($car_info);
4.  It'l work in the javascript, all you have to do is set it in the image url in the template.

**Comment by redman-racer** [comment]
cars['thumbnail_url'] works in garage_new, and the garage is now currently working post MVC update
